export const projects = [
  {
    name: "InReach",
    title: "Employee",
    link: "https://www.inreach.gg/",
    images: "/images/projects/inreach.png",
    tech: [
      "Web Design",
      "Front End Development",
      "UI/UX Design",
      "TypeScript",
      "Tailwind",
    ],
  },
  {
    name: "Ethereum",
    title: "Contributor",
    desc: "Ethereum.org is the official platform for Ethereum, a leading blockchain technology for decentralized applications and smart contracts. It provides valuable resources, guides, and insights for developers, enthusiasts, and investors, empowering them to explore and contribute to the world of decentralized finance and blockchain innovations.",
    link: "https://ethereum.org/en/",
    git: "https://github.com/ImMiguelP/ethereum-org-website",
    images: "/images/projects/eth1.png",
    tech: [
      "Web Design",
      "Front End Development",
      "UI/UX Design",
      "TypeScript",
      "Chakra-UI",
    ],
  },
  {
    name: "Musy",
    title: "Contributor",
    link: "https://musy.one/",
    git: "https://github.com/laurentlucian/musy",
    images: "/images/projects/musy2.png",
    tech: [
      "Web Design",
      "Front End Development",
      "UI/UX Design",
      "Remix",
      "TypeScript",
      "Chakra-UI",
      "Prisma",
    ],
  },
  {
    name: "Instagram Clone",
    title: "Creator",
    git: "https://github.com/ImMiguelP/instagram-clone",
    images: "/images/projects/ig1.png",
    tech: [
      "Web Design",
      "Front End Development",
      "UI/UX Design",
      "React",
      "JavaScript",
      "Chakra-UI",
      "Supabase",
    ],
  },
  {
    name: "Portfolio",
    title: "Creator",
    git: "https://github.com/ImMiguelP/Port",
    tech: [
      "Web Design",
      "Front End Development",
      "UI/UX Design",
      "Next.JS",
      "TypeScript",
      "Chakra-UI",
    ],
  },
];
